# Generated by Django 4.2.7 on 2025-12-17 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_env_config', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepConfig',
            fields=[
                ('config_block_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('config_block', models.JSONField()),
                ('function', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('function', models.CharField(max_length=64)),
                ('depends_on', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('config_block_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Queue.stepconfig')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Queue.job')),
            ],
            options={
                'unique_together': {('job', 'identifier')},
            },
        ),
    ]
